builders:
  resource_id:
    import: "package:resource_id/build_runner/build_runner_builder.dart"
    builder_factories: ["resourceId"]
    auto_apply: dependents
    build_extensions:
      main.dart: ["."]
    applies_builders:
      - resource_id|
    defaults:
      release_options:
        outputStyle: compressed